name: bus_tracker
description: "Otobüs canlı takip Flutter uygulaması"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  provider: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: InterVariable
      fonts:
        - asset: assets/fonts/InterVariable.ttf
